name: 'Conda Package Publish Action'
description: 'Build and Publish conda package'
author: 'Andrew Prokhorenkov'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with project'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
runs:
  using: 'docker'
  image: 'Dockerfile'
