name: 'build-publish-anaconda'
description: 'Build and Publish anaconda package'
author: 'Thomas Arsouze'
branding:
  icon: 'package'
  color: 'green'
inputs:
  conda:
    description: "Directory with conda recipe. Default `.` ."
    required: false
    default: '.'
  condapython:
    description: 'Python3 minor version used for conda. Default `10`.'
    required: false
    default: '10'
  python:
    description: 'Python3 minor version used for building. Default `10`.'
    required: false
    default: '10'
  token:
    description: 'Anaconda access Token (required)'
    required: true
  channels:
    description: 'Optional Extra anaconda channels to use. Coma-separated syntax. Default `conda-forge`.'
    required: false
    default: 'conda-forge'
  publish:
    description: 'Whether we publish the package build on anaconda cloud or not. Default `true`.'
    required: false
    default: 'true'
  label:
    description: Label of conda package published. Default `main`.
    required: false
    default: main
  buildoptions:
    description: Build options for conda build.
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Check if meta.yml exists in ${{ inputs.conda }} directory
      id: check-meta
      working-directory: ./${{ inputs.conda }}
      run: |
        echo "::group::Checking the conda directory if the file meta.yaml exists"
        if [ ! -f meta.yaml ]; then
           echo "A meta.yaml file with the compilation instructions of the conda package was not found in ${{ inputs.conda }}."
           exit 1
        else
           echo "A meta.yaml file with the compilation instructions of the conda package was found in ${{ inputs.conda }}."
        fi
        echo "::endgroup::"
      shell: bash
    - name: Check if anaconda login information are available
      id: check-login
      if: ${{ inputs.publish == 'true' }}
      working-directory: ./${{ inputs.conda }}
      run: |
        echo "::group::Checking if the token variable is correclty set"
        if [[ "${{ inputs.token }}" == "" ]]; then
           echo "No token variable is set for upload."
           exit 1
        else
           echo "Token is correctly set."
        fi
        echo "::endgroup::"
      shell: bash
    - name: Setup Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.${{ inputs.condapython }}
        channels: ${{ inputs.channels }}
        auto-update-conda: false
        miniforge-version: latest
        conda-remove-defaults: "true"
    - name: Setup conda-build and anaconda-client
      run:  |
        echo "::group::Setup conda-build and anaconda-client"
        conda install -q conda-build anaconda-client conda-forge-pinning
        echo "::endgroup::"
      shell: bash -l {0}
    - name: Package compilation
      id: package-compilation
      working-directory: ./${{ inputs.conda }}
      run: |
        echo "::group::Conda packages building"
        export PYTHON_VERSION="3.${{ inputs.python }}"
        export GIT_DESCRIBE_TAG=$(git describe --tags --abbrev=0 || echo "no-tag")
        export CONFIG="$CONDA_PREFIX/conda_build_config.yaml"
        out_dir=$(mktemp -d conda-build-dir.XXXXXX)
        echo "Running 'conda build' with Python ${PYTHON_VERSION} and git tag ${GIT_DESCRIBE_TAG}"
        conda build . --output-folder "$out_dir" --python "$PYTHON_VERSION" -m "$CONFIG" ${{ inputs.buildoptions }}
        echo "out_dir=$out_dir" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"
      shell: bash -l {0}
    - name: Package uploading
      id: package-uploading
      if: ${{ inputs.publish == 'true' }}
      working-directory: ./${{ inputs.conda }}
      run: |
        echo "::group::Conda packages uploading"
        export ANACONDA_API_TOKEN=${{ inputs.token }}
        for BUILD_FILE in ${{ steps.package-compilation.outputs.out_dir }}/*/*; do
          if [ "${BUILD_FILE: -6}" == ".conda" ]; then
            echo "Upload package ${BUILD_FILE} to anaconda with label ${{ inputs.label }} on channel associated to the given token."
            anaconda upload --skip-existing --no-progress --label ${{ inputs.label }} ${BUILD_FILE}
          fi
        done
        echo "::endgroup::"
      shell: bash -l {0}
