name: 'setup-ci'
description: 'Setup CI variables according to calling context'
author: 'Christian Fournier'

inputs:
  conda-directory:
    description: "Sub-directory containing conda recipe (meta.yaml). Default `conda`."
    required: false
    default: 'conda'
  python-minor-version:
    description: 'List of python minor versions to build/deploy the package. Default is "[9, 10, 11, 12]".'
    default: "[9, 10, 11, 12]"
    required: false
  operating-system:
    description: 'List of OS to build/deploy the package. Default is [ubuntu-latest, macos-latest, macos-13, windows-latest].'
    default: '["ubuntu-latest", "macos-latest", "macos-13", "windows-latest"]'
    required: false
  force-full-matrix:
    description: 'Force full matrix execution whatever the context.'
    default: 'false'
    required: false
  dev-label:
    description: 'Anaconda label for development versions.'
    default: 'dev'
    required: false
  rc-label:
    description: 'Anaconda label for release candidates.'
    default: 'rc'
    required: false
  default-label:
    description: 'Default Anaconda label.'
    default: 'main'
    required: false
  force-default-label:
    description: 'Force all publications on default label.'
    default: 'false'
    required: false
  force-no-promotion:
    description: 'Force skipping promotion.'
    default: 'false'
    required: false
  force-no-publication:
    description: 'Force skipping publication.'
    default: 'false'
    required: false
  simulated-ref:
    description: '(debug) use this ref instead of actual context'
    required: false
    default: ''
  simulated-event:
    description: '(debug) use this event instead of actual context'
    required: false
    default: ''
    
outputs:
  is_master:
    description: "True if the ref is main or master"
    value: ${{ steps.context.outputs.is_master }}
  is_branch:
    description: "True if the ref is a non-main branch"
    value: ${{ steps.context.outputs.is_branch }}
  is_release:
    description: "True if the event is a GitHub release"
    value: ${{ steps.context.outputs.is_release }}
  is_tag:
    description: "True if the ref is a version tag"
    value: ${{ steps.context.outputs.is_tag }}
  is_pr:
    description: "True if the event is a pull request"
    value: ${{ steps.context.outputs.is_pr }}
  os:
    description: "Selected OS matrix"
    value: ${{ steps.set-matrix.outputs.os }}
  py:
    description: "Selected Python matrix"
    value: ${{ steps.set-matrix.outputs.py }}

runs:
  using: "composite"
  steps:
    - name: Check context requirements
      shell: bash
      run: |
        if [ -z "$GITHUB_EVENT_NAME" ]; then
          echo "GITHUB_EVENT_NAME is not set!"
          exit 1
        fi
        if [ -z "$GITHUB_REF" ]; then
          echo "GITHUB_REF is not set!"
          exit 1
        fi
    - name: Detect Git Context
      id: context
      shell: bash
      run: |
        ref="${{ inputs.simulated-ref || env.GITHUB_REF }}"
        event="${{ inputs.simulated-event || env.GITHUB_EVENT_NAME }}"
        is_master=false
        is_branch=false
        is_release=false
        is_tag=false
        is_pr=false
        if [[ "$event" == "pull_request" ]]; then
          is_pr=true
        fi
        if [[ "$ref" == "refs/heads/master" || "$ref" == "refs/heads/main" ]]; then
          is_master=true
        fi
        if [[ "$ref" == refs/heads/* && "$is_master" == false ]]; then
          is_branch=true
        fi
        if [[ "$ref" == refs/tags/v* ]]; then
          is_tag=true
        fi
        if [[ "$event" == "release" ]]; then
          is_release=true
        fi
        echo "Context:"
        echo "  Push on branch: $is_branch"
        echo "  Push on master: $is_master"
        echo "  Pull request:   $is_pr"
        echo "  Push tag:       $is_tag"
        echo "  Release:        $is_release"
        echo "is_master=$is_master" >> "$GITHUB_OUTPUT"
        echo "is_branch=$is_branch" >> "$GITHUB_OUTPUT"
        echo "is_release=$is_release" >> "$GITHUB_OUTPUT"
        echo "is_tag=$is_tag" >> "$GITHUB_OUTPUT"
        echo "is_pr=$is_pr" >> "$GITHUB_OUTPUT"
    - name: Set OS × Python matrix depending on event
      id: set-matrix
      shell: bash
      run: |
        os="${{ inputs.operating-system }}"
        py="${{ inputs.python-minor-version }}"
        force="${{ inputs.force-full-matrix }}"
        is_branch="${{ steps.context.outputs.is_branch }}"
        is_tag="${{ steps.context.outputs.is_tag }}"
        if [[ "$force" != "true" ]]; then
          if [[ "$is_branch" == "true" ]]; then
            os='["ubuntu-latest"]'
          fi
          if [[ "$is_tag" != "true" ]]; then
            py='[12]'
          fi
        fi
        echo "Selected operating systems: $os"
        echo "Selected Python minor versions: $py"
        echo "os=$os" >> "$GITHUB_OUTPUT"
        echo "py=$py" >> "$GITHUB_OUTPUT"

    # - name: Check if meta.yml exists in ${{ inputs.conda }} directory
      # id: check-meta
      # working-directory: ./${{ inputs.conda }}
      # run: |
        # echo "::group::Checking the conda directory if the file meta.yaml exists"
        # if [ ! -f meta.yaml ]; then
           # echo "A meta.yaml file with the compilation instructions of the conda package was not found in ${{ inputs.conda }}."
           # exit 1
        # else
           # echo "A meta.yaml file with the compilation instructions of the conda package was found in ${{ inputs.conda }}."
        # fi
        # echo "::endgroup::"
      # shell: bash