name: 'promote-to-main'
description: 'Promote package to main'
author: 'Christian Fournier'
branding:
  icon: 'package'
  color: 'green'
inputs:
  token:
    description: 'Anaconda access Token (required)'
    required: true
  promote_from:
    description: 'Source label'
    default: 'rc'
    required: false
  promote_to:
    description: 'Target label'
    default: 'main'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up Anaconda
      shell: bash
      run: |
        conda install -q anaconda-client
    - name: Extract name and version from tag
      id: extract
      shell: bash
      run: |
        export ANACONDA_API_TOKEN=${{ inputs.token }}
        USER=$(anaconda whoami | awk '{print $4}')
        TAG=${GITHUB_REF#refs/tags/}
        NAME=$(echo "$TAG" | cut -d'-' -f1)
        VERSION=$(echo "$TAG" | cut -d'-' -f2-)
        echo "user=$USER" >> $GITHUB_OUTPUT
        echo "name=$NAME" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Promote files from ${{ inputs.promote_from }} to ${{ inputs.promote_to }}
      shell: bash
      run: |
        export ANACONDA_API_TOKEN=${{ inputs.token }}
        anaconda move \
          ${{ steps.extract.outputs.user }}/${{ steps.extract.outputs.name }}/${{ steps.extract.outputs.version }}\
          --from-label ${{ inputs.promote_from }} \
          --to-label ${{ inputs.promote_to }}
