{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}

package:
  name: dummy-package
  version: {{ version }}

source:
  path: .

build:
  string: py{{ PY_VER }}

about:
  home: "https://example.com"
  license: MIT
  summary: "A dummy package for testing actions."

