name: Generate Docs PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # required, otherwise it will fail to lock ref on auto-commit
      matrix:
        include:
          - readme: './doc/actions/setup-ci/README.md'
            source: './setup-ci/action.yml'
          - readme: './doc/workflows/test_setup/README.md'
            source: './.github/workflows/test_setup.yml'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: github-actions-docs
        uses: tjtharrison/github-actions-docs@1
        with:
          OUTPUT_FILE_NAME: ${{ matrix.readme }}
          ACTION_FILE_NAME: ${{ matrix.source }}
