name: Generate Docs PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docs for setup-ci
        uses: npalm/action-docs-action@v3.1.2
        with:
          readme: './doc/actions/setup-ci/README.md'
          source-file: './setup-ci/action.yml'
      - name: Generate docs for workflows
        uses: npalm/action-docs-action@v3.1.2
        with:
          readme: './doc/workflows/test_setup/README.md'
          source-file: './github/workflows/test_setup.yml'
      - name: Show git status
        run: |
          git status
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'update generated docs'
          branch: docs/update-generated-docs
          title: 'Update generated docs'
          body: 'This PR contains updated documentation generated from the latest action and workflow YAML.'