name: Test Composite Action setup-ci

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to simulate (e.g., refs/heads/main, refs/tags/v1.0.0)"
        required: false
        default: "refs/heads/feature/test"
      event_name:
        description: "Event name to simulate (e.g., push, pull_request)"
        required: false
        default: "push"
        
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: "refs/heads/feature"
            event: "push"
          - ref: "refs/heads/feature"
            event: "pull_request"
          - ref: "refs/heads/main"
            event: "push"
          - ref: "refs/tags/v1.0.0"
            event: "push"
          - event: "release"
    env:
      GITHUB_REF: ${{ matrix.ref }}
      GITHUB_EVENT_NAME: ${{ matrix.event }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run setup-ci for different scenarios
        id: setci
        uses: openalea/action-build-publish-anaconda/setup-ci@setup_action
      - name: Print output
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "is_branch:  ${{ steps.setci.outputs.is_branch }}"
          echo "is_master:  ${{ steps.setci.outputs.is_master }}"
          echo "is_pr:      ${{ steps.setci.outputs.is_pr }}"
          echo "is_tag:     ${{ steps.setci.outputs.is_tag }}"
          echo "is_release: ${{ steps.setci.outputs.is_release }}"
          echo "os:         ${{ steps.setci.outputs.os }}"
          echo "py:         ${{ steps.setci.outputs.py }}"