name: Test Dry run

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo hosting action
        uses: actions/checkout@v4
      - name: Run cleanup-action on dummy-package
        id: clean
        uses: ./actions/cleanup-label
        with:
          target-package: 'dummy-package'
          target-label: 'dev'
          target-version: '2.0.0'
          anaconda_token: ${{ secrets.ANACONDA_TOKEN }}


