name: Test CI on Dummy Package

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'github.ref to simulate (eg: refs/heads/master, refs/tags/v*, ...)'
        required: false
        default: 'refs/heads/master'

      git-event:
        description: 'github.event_name to simulate (eg push, release)'
        required: false
        default: 'push'
        
jobs:
  run-on-dummy:
    uses: ./.github/workflows/openalea_ci.yml
    with:
      conda-directory: "dummy_pkg"
      force-ref: ${{ inputs.git-ref }}
      force-event: ${{ inputs.git-event }}
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
