name: Test Composite Action setup-ci

on:
  workflow_dispatch:
        
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: "refs/heads/feature"
            event: "push"
          - ref: "refs/heads/feature"
            event: "pull_request"
          - ref: "refs/heads/main"
            event: "push"
          - ref: "refs/tags/v1.0.0"
            event: "push"
          - ref: "refs/tags/v1.0.0"
            event: "release"
    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_EVENT_NAME: ${{ github.event }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run setup-ci for different scenarios
        id: setci
        uses: ./setup-ci
        with:
          simulated-ref: ${{ matrix.ref }}
          simulated-event: ${{ matrix.event }}
      - name: Test results
        run: |
          echo "simulated ref: ${{ matrix.ref }}"
          echo "simulated event: ${{ matrix.event }}"
          echo "is_branch:  ${{ steps.setci.outputs.is_branch }}"
          echo "is_master:  ${{ steps.setci.outputs.is_master }}"
          echo "is_pr:      ${{ steps.setci.outputs.is_pr }}"
          echo "is_tag:     ${{ steps.setci.outputs.is_tag }}"
          echo "is_release: ${{ steps.setci.outputs.is_release }}"
          echo "os:         ${{ steps.setci.outputs.os }}"
          echo "py:         ${{ steps.setci.outputs.py }}"