name: Test Composite Action setup-ci

on:
  workflow_dispatch:
        
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: "refs/heads/feature"
            event: "push"
          - ref: "refs/heads/feature"
            event: "pull_request"
          - ref: "refs/heads/main"
            event: "push"
          - ref: "refs/tags/vx.x.x"
            event: "push"
          - ref: "refs/tags/vx.x.x"
            event: "release"
    env:
      GITHUB_REF: ""
      GITHUB_EVENT_NAME: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run setup-ci for different scenarios
        id: setci
        uses: ./setup-ci
        with:
          simulated-ref: ${{ matrix.ref }}
          simulated-event: ${{ matrix.event }}
      - name: Test results
        run: |
          echo "simulated ref:   ${{ matrix.ref }}"
          echo "simulated event: ${{ matrix.event }}"
          echo "build_os:     ${{ steps.setci.outputs.build_os }}"
          echo "build_py:     ${{ steps.setci.outputs.build_py }}"
          echo "publish:      ${{ steps.setci.outputs.publish }}"
          echo "promote:      ${{ steps.setci.outputs.promote }}"
          echo "publish_on:   ${{ steps.setci.outputs.publish_on }}"
          echo "promote_from: ${{ steps.setci.outputs.promote_from }}"
          echo "promote_to:   ${{ steps.setci.outputs.promote_to }}"
          echo "version:      ${{ steps.setci.outputs.version }}"